# Stack Overflow Survey Analysis

In [2]:
import pandas as pd

In [3]:
df = pd.read_csv('survey_results_public.csv', index_col='ResponseId')
df_schema = pd.read_csv('survey_results_schema.csv', index_col='qname')

In [4]:
df

,MainBranch,Employment,RemoteWork,CodingActivities,EdLevel,LearnCode,LearnCodeOnline,LearnCodeCoursesCert,YearsCode,YearsCodePro,...,TimeSearching,TimeAnswering,Onboarding,ProfessionalTech,TrueFalse_1,TrueFalse_2,TrueFalse_3,SurveyLength,SurveyEase,ConvertedCompYearly
ResponseId,,,,,,,,,,,,,,,,,,,,,
1,None of these,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,I am a developer by profession,"Employed, full-time",Fully remote,Hobby;Contribute to open-source projects,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Too long,Difficult,NaN
3,"I am not primarily a developer, but I write co...","Employed, full-time","Hybrid (some remote, some in-person)",Hobby,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Books / Physical media;Friend or family member...,Technical documentation;Blogs;Programming Game...,NaN,14,5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Appropriate in length,Neither easy nor difficult,40205.0
4,I am a developer by profession,"Employed, full-time",Fully remote,I don’t code outside of work,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)","Books / Physical media;School (i.e., Universit...",NaN,NaN,20,17,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Appropriate in length,Easy,215232.0
5,I am a developer by profession,"Employed, full-time","Hybrid (some remote, some in-person)",Hobby,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)","Other online resources (e.g., videos, blogs, f...",Technical documentation;Blogs;Stack Overflow;O...,NaN,8,3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Too long,Easy,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
73264,I am a developer by profession,"Employed, full-time",Fully remote,Freelance/contract work,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Books / Physical media;Other online resources ...,Technical documentation;Blogs;Written Tutorial...,Udemy,8,5,...,30-60 minutes a day,Less than 15 minutes a day,Just right,DevOps function;Microservices;Developer portal...,Yes,Yes,Yes,Too long,Easy,NaN
73265,I am a developer by profession,"Employed, full-time",Full in-person,Hobby,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)","Other online resources (e.g., videos, blogs, f...",Technical documentation;Blogs;Written Tutorial...,Coursera;Udemy;Udacity,6,5,...,15-30 minutes a day,60-120 minutes a day,Very long,None of these,No,Yes,Yes,Too long,Easy,NaN
73266,"I am not primarily a developer, but I write co...","Employed, full-time","Hybrid (some remote, some in-person)",Hobby;School or academic work,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Books / Physical media;Other online resources ...,Technical documentation;Programming Games;Stac...,Udemy;Codecademy;Pluralsight;edX,42,33,...,30-60 minutes a day,60-120 minutes a day,Just right,None of these,No,No,No,Appropriate in length,Easy,NaN
73267,I am a developer by profession,"Employed, full-time","Hybrid (some remote, some in-person)",Hobby,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Books / Physical media;On the job training,NaN,NaN,50,31,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Appropriate in length,Easy,NaN
73268,"I used to be a developer by profession, but no...","Independent contractor, freelancer, or self-em...",Fully remote,Hobby;Contribute to open-source projects;Boots...,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Books / Physical media;Friend or family member...,Technical documentation;Blogs;Programming Game...,Udemy;Pluralsight,16,5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Appropriate in length,Easy,NaN

In [5]:
df.columns

Index(['MainBranch', 'Employment', 'RemoteWork', 'CodingActivities', 'EdLevel',
       'LearnCode', 'LearnCodeOnline', 'LearnCodeCoursesCert', 'YearsCode',
       'YearsCodePro', 'DevType', 'OrgSize', 'PurchaseInfluence', 'BuyNewTool',
       'Country', 'Currency', 'CompTotal', 'CompFreq',
       'LanguageHaveWorkedWith', 'LanguageWantToWorkWith',
       'DatabaseHaveWorkedWith', 'DatabaseWantToWorkWith',
       'PlatformHaveWorkedWith', 'PlatformWantToWorkWith',
       'WebframeHaveWorkedWith', 'WebframeWantToWorkWith',
       'MiscTechHaveWorkedWith', 'MiscTechWantToWorkWith',
       'ToolsTechHaveWorkedWith', 'ToolsTechWantToWorkWith',
       'NEWCollabToolsHaveWorkedWith', 'NEWCollabToolsWantToWorkWith',
       'OpSysProfessional use', 'OpSysPersonal use', 'VersionControlSystem',
       'VCInteraction', 'VCHostingPersonal use', 'VCHostingProfessional use',
       'OfficeStackAsyncHaveWorkedWith', 'OfficeStackAsyncWantToWorkWith',
       'OfficeStackSyncHaveWorkedWith', 'OfficeStackSyncWantToWorkWith',
       'Blockchain', 'NEWSOSites', 'SOVisitFreq', 'SOAccount', 'SOPartFreq',
       'SOComm', 'Age', 'Gender', 'Trans', 'Sexuality', 'Ethnicity',
       'Accessibility', 'MentalHealth', 'TBranch', 'ICorPM', 'WorkExp',
       'Knowledge_1', 'Knowledge_2', 'Knowledge_3', 'Knowledge_4',
       'Knowledge_5', 'Knowledge_6', 'Knowledge_7', 'Frequency_1',
       'Frequency_2', 'Frequency_3', 'TimeSearching', 'TimeAnswering',
       'Onboarding', 'ProfessionalTech', 'TrueFalse_1', 'TrueFalse_2',
       'TrueFalse_3', 'SurveyLength', 'SurveyEase', 'ConvertedCompYearly'],
      dtype='object')

In [6]:
# Get years of coding for respondand 1 to 50 
df.loc[1:50, 'YearsCode']

ResponseId
1     NaN
2     NaN
3      14
4      20
5       8
6      15
7       3
8       1
9       6
10     37
11      5
12     12
13     12
14     22
15     11
16      4
17      7
18     13
19     36
20      2
21      1
22      5
23     25
24     10
25     40
26     16
27     10
28      4
29     20
30     27
31    NaN
32     24
33      3
34      8
35      6
36     16
37     12
38     19
39      2
40     24
41     20
42      3
43      4
44     15
45      6
46      4
47      7
48      6
49     40
50      7
Name: YearsCode, dtype: object

In [7]:
df_schema

,qid,question,force_resp,type,selector
qname,,,,,
S0,QID16,"<div><span style=""font-size:19px;""><strong>Hel...",False,DB,TB
MetaInfo,QID12,Browser Meta Info,False,Meta,Browser
S1,QID1,"<span style=""font-size:22px; font-family: aria...",False,DB,TB
MainBranch,QID2,Which of the following options best describes ...,True,MC,SAVR
Employment,QID296,Which of the following best describes your cur...,False,MC,MAVR
...,...,...,...,...,...
Frequency_2,QID290,Interacting with people outside of your immedi...,NaN,MC,MAVR
Frequency_3,QID290,Encountering knowledge silos (where one indivi...,NaN,MC,MAVR
TrueFalse_1,QID294,Are you involved in supporting new hires durin...,NaN,MC,MAVR
TrueFalse_2,QID294,Do you use learning resources provided by your...,NaN,MC,MAVR
TrueFalse_3,QID294,Does your employer give you time to learn new ...,NaN,MC,MAVR

In [8]:
df_schema['question']

qname
S0             <div><span style="font-size:19px;"><strong>Hel...
MetaInfo                                       Browser Meta Info
S1             <span style="font-size:22px; font-family: aria...
MainBranch     Which of the following options best describes ...
Employment     Which of the following best describes your cur...
                                     ...
Frequency_2    Interacting with people outside of your immedi...
Frequency_3    Encountering knowledge silos (where one indivi...
TrueFalse_1    Are you involved in supporting new hires durin...
TrueFalse_2    Do you use learning resources provided by your...
TrueFalse_3    Does your employer give you time to learn new ...
Name: question, Length: 79, dtype: object

In [9]:
df_schema.loc['CodingActivities','question']

'Which of the following best describes the code you write outside of work? Select all that apply.'

In [10]:
# Filtering data
#filter if the employment is full time
filt= (df['Employment'] == 'Employed, full-time')
# filter based on list of countries
countries = ['Canada', 'France', 'United States of America']
filt2= df['Country'].isin(countries)
#filter based on string
filt3= df['LanguageHaveWorkedWith'].str.contains('Python', na=False)

df.loc[filt3, ['Employment','ConvertedCompYearly','Country','LanguageHaveWorkedWith','YearsCodePro','EdLevel']]

,Employment,ConvertedCompYearly,Country,LanguageHaveWorkedWith,YearsCodePro,EdLevel
ResponseId,,,,,,
3,"Employed, full-time",40205.0,United Kingdom of Great Britain and Northern I...,C#;C++;HTML/CSS;JavaScript;Python,5,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)"
7,"Student, part-time",NaN,India,C++;HTML/CSS;JavaScript;PHP;Python;TypeScript,NaN,"Secondary school (e.g. American high school, G..."
12,"Employed, full-time;Independent contractor, fr...",194400.0,United States of America,C#;HTML/CSS;JavaScript;PowerShell;Python;Rust;SQL,10,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)"
15,"Employed, full-time;Independent contractor, fr...",110000.0,United States of America,HTML/CSS;JavaScript;PHP;Python;R;Ruby;Scala,5,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)"
17,"Employed, full-time",19224.0,Czech Republic,C#;Java;PHP;Python;R,4,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)"
...,...,...,...,...,...,...
73258,"Student, full-time",NaN,India,C;Python;SQL,NaN,"Secondary school (e.g. American high school, G..."
73262,"Employed, full-time",NaN,France,Bash/Shell;HTML/CSS;Java;JavaScript;Python;SQL...,2,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)"
73264,"Employed, full-time",NaN,Nigeria,Bash/Shell;Dart;JavaScript;PHP;Python;SQL;Type...,5,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)"
73265,"Employed, full-time",NaN,United States of America,Bash/Shell;HTML/CSS;JavaScript;Python;SQL,5,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)"
73266,"Employed, full-time",NaN,United States of America,HTML/CSS;JavaScript;PHP;Python;SQL,33,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)"

In [11]:

df.loc[~filt]

,MainBranch,Employment,RemoteWork,CodingActivities,EdLevel,LearnCode,LearnCodeOnline,LearnCodeCoursesCert,YearsCode,YearsCodePro,...,TimeSearching,TimeAnswering,Onboarding,ProfessionalTech,TrueFalse_1,TrueFalse_2,TrueFalse_3,SurveyLength,SurveyEase,ConvertedCompYearly
ResponseId,,,,,,,,,,,,,,,,,,,,,
1,None of these,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,"I am not primarily a developer, but I write co...","Student, full-time",NaN,NaN,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)","Books / Physical media;School (i.e., Universit...",NaN,NaN,15,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Appropriate in length,Easy,NaN
7,I code primarily as a hobby,"Student, part-time",NaN,NaN,"Secondary school (e.g. American high school, G...","Other online resources (e.g., videos, blogs, f...",Stack Overflow;Video-based Online Courses,NaN,3,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Appropriate in length,Easy,NaN
8,I am a developer by profession,"Not employed, but looking for work",NaN,NaN,Some college/university study without earning ...,Online Courses or Certification,NaN,Coursera;Udemy,1,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Appropriate in length,Easy,NaN
10,I am a developer by profession,"Independent contractor, freelancer, or self-em...",Fully remote,Hobby;Contribute to open-source projects;Boots...,Some college/university study without earning ...,Books / Physical media;Other online resources ...,Technical documentation;Blogs;Written Tutorial...,NaN,37,30,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Appropriate in length,Easy,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
73257,I am a developer by profession,"Student, part-time;Employed, part-time","Hybrid (some remote, some in-person)",School or academic work,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Books / Physical media;Other online resources ...,Technical documentation;Stack Overflow;Online ...,Coursera;Udemy,9,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Appropriate in length,Easy,NaN
73258,I am learning to code,"Student, full-time",NaN,NaN,"Secondary school (e.g. American high school, G...",Books / Physical media;Other online resources ...,Technical documentation;Blogs;Written Tutorial...,NaN,7,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Too short,Easy,NaN
73261,I am a developer by profession,"Employed, full-time;Student, part-time","Hybrid (some remote, some in-person)",School or academic work,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)","School (i.e., University, College, etc)",NaN,NaN,8,NaN,...,15-30 minutes a day,30-60 minutes a day,Very long,DevOps function;Developer portal or other cent...,No,No,Yes,Appropriate in length,Easy,NaN
73263,I am learning to code,"Student, full-time;Employed, part-time","Hybrid (some remote, some in-person)",School or academic work,"Secondary school (e.g. American high school, G...","Other online resources (e.g., videos, blogs, f...",Technical documentation;Written Tutorials;Stac...,NaN,4,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Appropriate in length,Neither easy nor difficult,NaN
73268,"I used to be a developer by profession, but no...","Independent contractor, freelancer, or self-em...",Fully remote,Hobby;Contribute to open-source projects;Boots...,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Books / Physical media;Friend or family member...,Technical documentation;Blogs;Programming Game...,Udemy;Pluralsight,16,5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Appropriate in length,Easy,NaN

In [12]:
#rename a column
df.rename(columns={'ConvertedCompYearly':'Annual_Salary_USD'}, inplace=True)
df['Annual_Salary_USD']
#update values in column using map function
#df['Hobbyist'].map({'Yes:True, 'No': False})

ResponseId
1             NaN
2             NaN
3         40205.0
4        215232.0
5             NaN
           ...
73264         NaN
73265         NaN
73266         NaN
73267         NaN
73268         NaN
Name: Annual_Salary_USD, Length: 73268, dtype: float64

In [13]:
df.sort_values(by=['Country', 'Annual_Salary_USD'],ascending=[True, False],inplace=True)
df[['Country', 'Annual_Salary_USD']].head(100)

                Country  Annual_Salary_USD
ResponseId
38513       Afghanistan           158484.0
43640       Afghanistan            92448.0
6892        Afghanistan            15600.0
43691       Afghanistan            13212.0
2449        Afghanistan            10894.0
...                 ...                ...
68078           Albania               36.0
5832            Albania                NaN
7679            Albania                NaN
9650            Albania                NaN
10347           Albania                NaN

[100 rows x 2 columns]

In [14]:
df.describe()

,CompTotal,VCHostingPersonal use,VCHostingProfessional use,WorkExp,Annual_Salary_USD
count,3.842200e+04,0.0,0.0,36769.000000,3.807100e+04
mean,2.342434e+52,NaN,NaN,10.242378,1.707613e+05
std,4.591478e+54,NaN,NaN,8.706850,7.814132e+05
min,0.000000e+00,NaN,NaN,0.000000,1.000000e+00
25%,3.000000e+04,NaN,NaN,4.000000,3.583200e+04
50%,7.750000e+04,NaN,NaN,8.000000,6.784500e+04
75%,1.540000e+05,NaN,NaN,15.000000,1.200000e+05
max,9.000000e+56,NaN,NaN,50.000000,5.000000e+07

In [15]:
df['Ethnicity'].value_counts(normalize=True)

European                                                                      0.210323
White                                                                         0.196232
White;European                                                                0.125140
Indian                                                                        0.075424
Asian                                                                         0.048162
                                                                                ...
White;European;Middle Eastern;North African;Multiracial                       0.000014
Or, in your own words:;Middle Eastern;Multiracial                             0.000014
European;Middle Eastern;Ethnoreligious group;Multiracial                      0.000014
Indian;Middle Eastern;Multiracial                                             0.000014
Indian;European;Asian;East Asian;Southeast Asian;South Asian;Central Asian    0.000014
Name: Ethnicity, Length: 1055, dtype: float64

In [16]:
country_grp = df.groupby(['Country'])
country_grp.get_group('Somalia')
#country_grp['Employment'].value_counts()

,MainBranch,Employment,RemoteWork,CodingActivities,EdLevel,LearnCode,LearnCodeOnline,LearnCodeCoursesCert,YearsCode,YearsCodePro,...,TimeSearching,TimeAnswering,Onboarding,ProfessionalTech,TrueFalse_1,TrueFalse_2,TrueFalse_3,SurveyLength,SurveyEase,Annual_Salary_USD
ResponseId,,,,,,,,,,,,,,,,,,,,,
28470,I am a developer by profession,"Employed, full-time","Hybrid (some remote, some in-person)",Contribute to open-source projects;Freelance/c...,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)","School (i.e., University, College, etc);On the...",NaN,Coursera;Codecademy;Pluralsight;edX;Udacity,7,5,...,15-30 minutes a day,15-30 minutes a day,Just right,None of these,Yes,No,Yes,Appropriate in length,Neither easy nor difficult,12000.0
21145,I am learning to code,"Employed, part-time",Full in-person,Hobby;Contribute to open-source projects;Boots...,Some college/university study without earning ...,"School (i.e., University, College, etc)",NaN,NaN,4,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Too long,Neither easy nor difficult,NaN
31940,I am a developer by profession,"Student, full-time",NaN,NaN,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Books / Physical media;Friend or family member,NaN,NaN,3,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Too long,Easy,NaN
42523,I am a developer by profession,"Employed, full-time","Hybrid (some remote, some in-person)",Hobby;Contribute to open-source projects;Freel...,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)","Other online resources (e.g., videos, blogs, f...",Technical documentation;Written Tutorials;Vide...,Pluralsight,5,1,...,15-30 minutes a day,Less than 15 minutes a day,Somewhat long,Developer portal or other central places to fi...,Yes,Yes,Yes,Appropriate in length,Easy,NaN
56102,I am a developer by profession,"Employed, full-time",Full in-person,I don’t code outside of work,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)","Friend or family member;School (i.e., Universi...",NaN,NaN,9,6,...,60-120 minutes a day,Less than 15 minutes a day,Somewhat short,NaN,NaN,NaN,NaN,Appropriate in length,Easy,NaN
60024,I am a developer by profession,"Employed, full-time",Full in-person,Hobby,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)","Friend or family member;School (i.e., Universi...",NaN,NaN,3,Less than 1 year,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Too long,Difficult,NaN
61514,I am a developer by profession,"Student, full-time",NaN,NaN,"Secondary school (e.g. American high school, G...",Online Courses or Certification,NaN,Other,10,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Appropriate in length,Neither easy nor difficult,NaN
62507,I am a developer by profession,"Employed, full-time",Full in-person,Hobby,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)","Other online resources (e.g., videos, blogs, f...",Technical documentation;Blogs;Stack Overflow;V...,Udemy,8,5,...,Over 120 minutes a day,15-30 minutes a day,Somewhat long,DevOps function;Continuous integration (CI) an...,Yes,No,Yes,Too long,Easy,NaN
66282,"I am not primarily a developer, but I write co...","Employed, full-time",Full in-person,Hobby,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)","School (i.e., University, College, etc)",NaN,NaN,4,Less than 1 year,...,Less than 15 minutes a day,Less than 15 minutes a day,Very long,None of these,No,No,No,Too long,Difficult,NaN
68674,I am a developer by profession,"Independent contractor, freelancer, or self-em...",Fully remote,Hobby;Bootstrapping a business;Freelance/contr...,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Online Courses or Certification;Coding Bootcamp,NaN,Udemy,6,3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Too long,Neither easy nor difficult,NaN
69012,I am a developer by profession,"Employed, full-time",Full in-person,Hobby,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Online Courses or Certification,NaN,Udemy,15,8,...,Less than 15 minutes a day,15-30 minutes a day,Very long,None of these,No,No,Yes,Appropriate in length,Neither easy nor difficult,NaN
70148,I am a developer by profession,"Independent contractor, freelancer, or self-em...",Full in-person,Freelance/contract work,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)","Other online resources (e.g., videos, blogs, f...",Technical documentation;Video-based Online Cou...,Udemy,4,2,...,15-30 minutes a day,15-30 minutes a day,Just right,NaN,No,Yes,Yes,Too long,Neither easy nor difficult,NaN

In [17]:
country_grp['Annual_Salary_USD'].agg(['median','mean'])

                                       median          mean
Country
Afghanistan                           10894.0  33914.666667
Albania                               15360.0  24895.148148
Algeria                                7440.0  12732.888889
Andorra                               76784.0  98003.125000
Angola                                 3073.5   6222.750000
...                                       ...           ...
Venezuela, Bolivarian Republic of...  12000.0  17079.400000
Viet Nam                              11388.0  37707.563830
Yemen                                 15000.0  17464.666667
Zambia                                 6612.0   8452.000000
Zimbabwe                              11400.0  87596.000000

[180 rows x 2 columns]

In [18]:
#df['YearsCode']= df['YearsCode'].astype(float)
df['YearsCode'].unique()
df['YearsCode'].replace('Less than 1 year', 0, inplace = True)
df['YearsCode'].replace('More than 50 years', 51, inplace = True)
df['YearsCode']= df['YearsCode'].astype(float)
df['YearsCode'].agg(['mean', 'median'])

mean      12.251307
median     9.000000
Name: YearsCode, dtype: float64

In [25]:
filt= df['Country']== 'Somalia'
Somalia_df = df.loc[filt]
Somalia_df.to_csv('C:\\Users\\Mohamoud\\github\\PythonCodes\\Data\\Somalia_df.csv')

In [26]:
filt= df['Country']== 'India'
India_df = df.loc[filt]
India_df.to_json('C:\\Users\\Mohamoud\\github\\PythonCodes\\Data\\India_df.json', orient = 'records', lines=True)

In [28]:
filt= df['Country']== 'Canada'
Canada_df = df.loc[filt]
Canada_df.to_csv('C:/Users/Mohamoud/github/PythonCodes/Data/Canada_df2.tsv', sep='\t')